name: Main CI

on:
  pull_request:
    branches:
      - main

jobs:
  deps-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Cache .stack
        id: cache-stack
        uses: actions/cache@v4.0.2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('**/package.yaml') }}-${{ hashFiles('**/stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-stack-
      - uses: haskell-actions/setup@v2.7.3
        name: Setup Haskell
        with:
          ghc-version: 8.10.4 # stack.yamlのresolverに合わせて更新してください
          enable-stack: true
          stack-version: latest
      - name: Install dependencies
        run: stack --system-ghc test --only-dependencies
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Cache .stack
        id: cache-stack
        uses: actions/cache@v4.0.2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('**/package.yaml') }}-${{ hashFiles('**/stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-stack-
      - uses: haskell-actions/setup@v2.7.3
        name: Setup Haskell
        with:
          ghc-version: 8.10.4 # stack.yamlのresolverに合わせて更新してください
          enable-stack: true
          stack-version: latest
      - name: Run test
        run: stack --system-ghc test --pedantic
